### ISSUE TITLE
Registred

### ISSUE THREAD

**Issue by DYMIANA** [timatet/dotnet-mvc#4]
Захожу во вкладку регистрации;
Ввожу следующие данные: 
![image](https://github.com/timatet/dotnet-mvc/assets/83299883/b95ce3db-28fe-4a2c-a804-7767aba136c1)
Пароль: qwerty
Получаю при нажатии кнопки создать аккаунт:
![image](https://github.com/timatet/dotnet-mvc/assets/83299883/bfa92808-e30f-4c9a-92fc-bf7cf0df56d8)

**Comment by timatet** [comment]
[d9c0dfb](https://github.com/timatet/dotnet-mvc/commit/d9c0dfb2f31ce0bf4a25f067ce3c493aff55ca92)

Актуальная конфигурация базы данных не соответсвовала изменениям, принятым в предыдущих коммитах.

**Comment by timatet** [comment]
Solved
